# Generated by Django 4.2.1 on 2023-11-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default=0, upload_to='profileimage'),
            preserve_default=False,
        ),
    ]
