# Generated by Django 4.2.1 on 2023-11-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default=False, upload_to='profileimage'),
        ),
    ]
