# Generated by Django 4.2.1 on 2023-11-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='image',
        ),
        migrations.AddField(
            model_name='customuser',
            name='userimage',
            field=models.ImageField(default='profileimage/profile.jpg', upload_to='profileimage'),
        ),
    ]
