# Generated by Django 4.2.1 on 2023-11-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_customuser_image_customuser_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='userimage',
            field=models.ImageField(default=0, upload_to='profileimage'),
        ),
    ]
