# Generated by Django 4.2.1 on 2023-11-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_userimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='isimage',
            field=models.BooleanField(default=False),
        ),
    ]
