# Generated by Django 4.2.1 on 2023-11-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customuser_isimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='isimage',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='userimage',
            field=models.ImageField(upload_to='profileimage'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userimage',
            field=models.ImageField(default='profileimage/profile.jpg', upload_to='profileimage'),
        ),
    ]
