# Generated by Django 4.2.1 on 2023-11-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_customuser_isimage_alter_customuser_userimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isimage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userimage',
            field=models.ImageField(upload_to='profileimage'),
        ),
    ]
